Term ordering diagrams refactor
vprover/vampire pull request #637
Opened 2024-12-23 15:57 UTC by mezpusz

I have refactored `OrderingComparator` and subclasses in order to have a relatively simple common framework for both `LPOComparator` and `KBOComparator`.

Additionally, the data structure itself is much more general (coined 'term ordering diagram' = TOD by Andrei), it can hold several data entries which need to be retrieved when some corresponding ordering constraints are true (for example, when we are looking for all demodulators that are oriented left-to-right under the current substitution). I haven't yet used this feature to much extent, but this allows improvements over demodulation, an eventual implementation of ground joinability, or similar redundancy criteria where some case distinction over term orderings is needed.

Some general data structures, such as `PartialOrdering` and `TermPartialOrdering` have been added which work over transitive closures of sets and terms, respectively.

There are some further improvements on the way, I just wanted to have a base branch set up towards merging with the current, already fixed and tested changes.

I think at some point we should also move term ordering related stuff into its own folder and namespace and rename this class into `TermOrderingDiagram`, but let's not increase the size of this PR.

According to regression and random sampled testing and cross checking all demodulation ordering checks, performance and correctness are unaffected as far as I can tell.

2024-12-23 16:20 UTC, mezpusz commented on Kernel/Ordering.hpp
> +#define DEBUG_ORDERING 0
Remove these debug checks once testing is done.

2024-12-28 10:16 UTC, MichaelRawson requested changes
Cool! I like the more general approach.

2024-12-28 10:16 UTC, MichaelRawson commented on Kernel/PartialOrdering.cpp
> +    void* mem = ALLOC_KNOWN(arrSize*sizeof(PoComp), "Kernel::PartialOrdering");
If the manual memory management is really necessary (is it? looks like `std::vector` to me), please replace the `ALLOC` macros, `array_new`, `array_delete` etc with just regular `new[]` and `delete[]`. `memcpy` could also be `std::copy` but nbd.

2024-12-28 10:16 UTC, MichaelRawson commented on Kernel/PartialOrdering.cpp
> + * Implements class PartialOrdering.
Could I have a couple lines explaining the approach taken here? I liked the one for `OrderingComparator`.

2025-01-02 07:45 UTC, quickbeam123 commented on Kernel/OrderingComparator.cpp
> +}
```
Kernel/OrderingComparator.cpp: In function ‘std::ostream& Kernel::operator<<(std::ostream&, const Kernel::OrderingComparator::Node::Tag&)’:
Kernel/OrderingComparator.cpp:472:1: warning: control reaches end of non-void function [-Wreturn-type]
  472 | }
      | ^
```

2025-01-02 07:46 UTC, quickbeam123 commented on Kernel/TermPartialOrdering.cpp
> +}
```
Kernel/TermPartialOrdering.cpp: In function ‘Kernel::PoComp Kernel::resultToPoComp(Kernel::Result, bool)’:
Kernel/TermPartialOrdering.cpp:55:1: warning: control reaches end of non-void function [-Wreturn-type]
   55 | }
      | ^
```

2025-01-02 07:50 UTC, quickbeam123 commented
So far, I only shared my compiler's warnings (as comments) and started a bit more performance testing.

2025-01-03 10:58 UTC, mezpusz commented on Indexing/Index.hpp
> +    comparator->insert({ { term, rhs, Ordering::GREATER } }, (void*)0x1);
I agree it looks shady, but good to know that it is actually UB! I will look for a better solution.

2025-01-03 12:14 UTC, mezpusz commented on Lib/Map.hpp
> +      : code(0)
Yes, there was a problem when copying or copy assigning a `Map`. Let me check it...

2025-01-03 12:15 UTC, mezpusz commented on Kernel/OrderingComparator.hpp
> +    static_assert(sizeof(uint64_t) == sizeof(int64_t));
More or less just the same size. But this could be replaced by the usual bit-setting idiom.

2025-01-03 12:21 UTC, MichaelRawson commented on Indexing/Index.hpp
> +    comparator->insert({ { term, rhs, Ordering::GREATER } }, (void*)0x1);
I'm not 100% sure - this [StackOverflow answer](https://stackoverflow.com/a/3839023) seems to partially corroborate my suspicions, but I'm not sure if it's OK to simply keep an invalid pointer as you don't do e.g. arithmetic with it. Also if it is indeed UB it is probably the most-OK UB I'll ever see, no sane platform will mind. But `uintptr_t` doesn't seem so bad as a compromise if you can make it work.

2025-01-03 12:21 UTC, MichaelRawson commented on Kernel/OrderingComparator.hpp
> +    static_assert(sizeof(uint64_t) == sizeof(int64_t));
I think it's OK, I was just surprised by the comparison to 64 bits.

2025-01-03 12:26 UTC, mezpusz commented on Inferences/ForwardDemodulation.cpp
> +#if DEBUG_ORDERING
Yes, certainly. But maybe factored out to the front.

2025-01-03 12:29 UTC, mezpusz commented on Lib/Map.hpp
> +      : code(0)
So the problem was `init`, in which we have an assertion for `code` being 0. This is only called if `other.occupied()` is non-zero, but `other.occupied()==other.code`, so `code` will be set up properly in this case, otherwise `code` is zero and we are also safe.

2025-01-03 12:37 UTC, mezpusz commented on Kernel/OrderingComparator.hpp
> +  void* next();
Yes, it would, unfortunately `Ordering::createComparator` being `virtual` prevents it. One solution would be to make it non-virtual which means we have to branch on the current options, I'm not sure how many times this function will be called though.

2025-01-03 12:38 UTC, mezpusz commented on Kernel/OrderingComparator.hpp
> +  void* next();
Another solution could be using a templated subclass which implements `check` and `insert` properly.

2025-01-03 12:45 UTC, mezpusz commented on Kernel/OrderingComparator.cpp
> +      // we can also safely use the original
You're right, I will add a less vague comment.

2025-01-03 12:57 UTC, mezpusz commented on Kernel/OrderingComparator.cpp
> +}
Clean up all ctors/copy assignment operators, please have a look.

2025-01-03 13:28 UTC, mezpusz commented on Inferences/ForwardDemodulation.cpp
> +        TermList rhsS = rhsApplied.apply();
Note: I changed this because we already have substitution-applying logic in the applicator classes above, but we can change it back if it shows unexpected slowdown. (I measured it only superficially so far.)

2025-01-03 14:46 UTC, mezpusz commented on Kernel/PartialOrdering.cpp
> +    void* mem = ALLOC_KNOWN(arrSize*sizeof(PoComp), "Kernel::PartialOrdering");
I changed it to `std::vector`. The code obviously got much better, the performance I could not yet measure properly, but there seems to be no significant difference.

2025-01-03 15:05 UTC, MichaelRawson commented on Kernel/OrderingComparator.cpp
> +}
Nice. I thought we might need an explicit `swap` implementation, but the default seems to do what we want.

2025-01-03 15:11 UTC, MichaelRawson approved these changes

2025-01-03 15:11 UTC, MichaelRawson commented
(remaining comments still stand but are not crucial for getting this in)

2025-01-03 16:50 UTC, quickbeam123 commented on Kernel/TermPartialOrdering.cpp
> +      ASSERTION_VIOLATION;
@MichaelRawson , don't we have a new official "pattern" for how to deal with enums and "potentially unlisted cases" / warnings?

2025-01-03 17:11 UTC, quickbeam123 commented on Inferences/BackwardDemodulation.cpp
>        return BwSimplificationRecord(0);
Maybe as a example explanation for what's change for the average ordering user, could you please quickly explain the transition here?

We had a boolean sounding name of a function with a bool result, now the new function returns `Result`. 

Are not using general `compare` because this one can be quicker about quickly failing on "less" side?

2025-01-04 09:27 UTC, mezpusz commented on Inferences/BackwardDemodulation.cpp
>        return BwSimplificationRecord(0);
The reason for this change is that I needed a function which can distinguish between greater, equal and the "rest" inside `OrderingComparator` and doing this relatively efficiently, so `compare` was out of question mostly because in some cases mostly for LPO it behaves badly. The old `isGreater` function with Boolean result did exactly this all along, this just wasn't exposed on the interface. We could of course have the original Boolean function separately as well, I just thought I don't want to increase the interface more.

2025-01-04 10:57 UTC, mezpusz commented on Kernel/TermPartialOrdering.cpp
> +      ASSERTION_VIOLATION;
I like the "assertion under `default` label" pattern more because it works regardless of what the function does outside of the `switch`, and there are several occurrences of this pattern in the code already. But I don't mind the other pattern either.

2025-01-04 11:00 UTC, mezpusz commented on Indexing/Index.hpp
> +    comparator->insert({ { term, rhs, Ordering::GREATER } }, (void*)0x1);
Yes, I see... Alternatively, how about inserting the pointer to the owner? From the caller side we just need any non-null value.

2025-01-04 11:01 UTC, MichaelRawson commented on Indexing/Index.hpp
> +    comparator->insert({ { term, rhs, Ordering::GREATER } }, (void*)0x1);
Ah, I see - sure! Valid non-null pointer seems fine to me.

2025-01-04 11:01 UTC, mezpusz commented on Kernel/OrderingComparator.hpp
> +  void* next();
Forget what I said in the previous comment, it does not make sense as we still have to create the object of subclass type, so we end up with the same problem (I think).

2025-01-04 11:08 UTC, MichaelRawson commented on Kernel/TermPartialOrdering.cpp
> +      ASSERTION_VIOLATION;
A slight annoyance is that if the enum is extended at some point the `default` label masks the warning we'd otherwise get - but you make a good point about the rest of the function. Such is life.

2025-01-04 11:18 UTC, MichaelRawson commented on Kernel/OrderingComparator.hpp
> +  void* next();
Now that I look, where is this interface actually used? It looks like it's only used in `ConditionalRedundancyHandler`, but somewhat trivially - so could this just be `bool next()` and not store any data at all?

2025-01-04 13:24 UTC, mezpusz commented on Kernel/OrderingComparator.hpp
> +  void* next();
You're right, it is not yet used, but I would like to retain this more general (albeit ugly) solution for further PRs. ;)

2025-01-04 13:25 UTC, mezpusz commented on Kernel/TermPartialOrdering.cpp
> +      ASSERTION_VIOLATION;
Ah, I forgot about this. Yes, then even if I don't expect the enum to be extended, let's have the other solution.

2025-01-04 13:48 UTC, MichaelRawson commented on Kernel/OrderingComparator.hpp
> +  void* next();
Ahah. OK, then let's fight about it later then. ;-)

2025-01-05 09:10 UTC, quickbeam123 commented on Inferences/ForwardDemodulation.cpp
> +        TermList rhsS = rhsApplied.apply();
I didn't find any change in performance just now...

2025-01-05 09:18 UTC, quickbeam123 commented on Inferences/BackwardDemodulation.cpp
>        return BwSimplificationRecord(0);
OK, I think I am getting there, but what's the contract for this function then?

if it says GREATER then we trust it, if is says EQUAL then we trust it, but if is says INCOMPARABLE or LESS it may be wrong (and it could possibly the other one of the two)?

Maybe we could think of a better name or have a big juicy comment explaining this?

2025-01-06 16:53 UTC, mezpusz commented on Inferences/BackwardDemodulation.cpp
>        return BwSimplificationRecord(0);
You're absolutely right that the name is confusing because it suggests a Boolean value. The comment explaining what the function does is also outdated, I will correct this in the next commit.

As for how many functions we should have and what should their names be. A truly Boolean function would remove the confusion in a few cases where we really care about "greaterness" like demodulation at the expense of having one more function, but in the end we still need the three-valued function at least inside `OrderingComparator`.

So I suggest something like `compareUnidirectional` instead of `isGreaterOrEq` and additionally explaining what unidirectional comparison means, which was already done in a comment in [LPO.cpp](https://github.com/vprover/vampire/blob/master/Kernel/LPO.cpp#L195). How do you like this solution?

2025-01-06 20:44 UTC, quickbeam123 commented on Inferences/BackwardDemodulation.cpp
>        return BwSimplificationRecord(0);
Yes, I think that would be a sufficient explanation / warning for the user! 

(I was actually confused, because the function IS currently only used in demodulation in the sense in which the boolean one would suffice. I guess your use case inside `OrderingComparator` is planned for the followup PR?)

2025-01-07 07:36 UTC, mezpusz commented on Inferences/BackwardDemodulation.cpp
>        return BwSimplificationRecord(0);
It is used [here](https://github.com/vprover/vampire/blob/term-ordering-diagrams/Kernel/OrderingComparator.cpp#L67), but I agree it's hard to catch in a hundreds-line-long new file!

2025-01-07 13:52 UTC, merged